name: clc.build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: aptgetready
      run: |
      sudo apt update
      sudo apt install -y \
      libx11-dev \
      libxcursor-dev \
      libxrandr-dev \
      libgl1-mesa-dev

    - name: installdep
      run: ./install_dependency.sh 
    - name: make
      run: make
    
